version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: 'aws-ecr/build-and-push-image-nginx'
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: YOUR-REPO-NAME-$CIRCLE_BRANCH
          tag: "${CIRCLE_SHA1}"
          path: .
          dockerfile: "/docker/nginx/Dockerfile.production"
          filters:
            branches:
              only:
                - main
                - develop

      - aws-ecr/build-and-push-image:
          name: 'aws-ecr/build-and-push-image-app'
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: YOUR-REPO-NAME-$CIRCLE_BRANCH
          tag: "${CIRCLE_SHA1}"
          path: .
          dockerfile: "/docker/php/Dockerfile.production"
          filters:
            branches:
              only:
                - main
                - develop

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image-nginx
            - aws-ecr/build-and-push-image-app
          family: 'YOUR-ECS-TASK-NAME'
          service-name: 'YOUR-ECS-SERVICE-NAME'
          cluster-name: 'YOUR-ECS-CLUSTERß-NAME'
          container-image-name-updates: 'container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/YOUR-REPO-NAME-${CIRCLE_BRANCH}:${CIRCLE_SHA1},container=app,image-and-tag=${AWS_ECR_ACCOUNT_URL}/YOUR-REPO-NAME-${CIRCLE_BRANCH}:${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main
                - develop