version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        repo: nginx_repository_name
        tag: "${CIRCLE_SHA1}"
        path: ./docker/nginx
        dockerfile: "Dockerfile.production"
        filters:
          branches:
            only:
              - main

      - aws-ecr/build-and-push-image:
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        repo: app_repository_name
        tag: "${CIRCLE_SHA1}"
        path: ./docker/php
        dockerfile: "Dockerfile.production"
        filters:
          branches:
            only:
              - main

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'yourTaskName'
          service-name: 'yourServiceName'
          cluster-name: 'yourClusterName'
          container-image-name-updates:
            - 'container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}'
            - 'container=app,image-and-tag=${AWS_ECR_ACCOUNT_URL}/app:${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main